name: custom_text_view
description: A customizable TextView widget for Flutter with font styling, padding, and layout support.
version: 1.0.1
license: MIT
homepage: https://github.com/vishalsharma-hovr/custom_text_view
repository: https://github.com/vishalsharma-hovr/custom_text_view
issue_tracker: https://github.com/vishalsharma-hovr/custom_text_view/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
